"""Feat: Add job_type to Job Table

Revision ID: ddcf9d8064b6
Revises: 0cf1f1a156e7
Create Date: 2025-06-26 08:11:57.390127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# Define the enums explicitly
job_type_enum = sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', name='job_type')
work_mode_enum = sa.Enum('ON_SITE', 'REMOTE', 'HYBRID', 'HYBRID_ON_SITE', 'REMOTE_ON_SITE_HYBRID', name='work_mode')

# revision identifiers, used by Alembic.
revision: str = 'ddcf9d8064b6'
down_revision: Union[str, None] = '0cf1f1a156e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### Create the enum types in PostgreSQL ###
    job_type_enum.create(op.get_bind(), checkfirst=True)
    work_mode_enum.create(op.get_bind(), checkfirst=True)

    # commands auto generated by Alembic - please adjust!
    op.add_column('jobs', sa.Column('job_type', job_type_enum, server_default='FULL_TIME', nullable=False))
    op.add_column('jobs', sa.Column('work_mode', work_mode_enum, server_default='ON_SITE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'job_type')

    # Drop the enum types
    work_mode_enum.drop(op.get_bind(), checkfirst=True)
    job_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
